### DISCUSSION TITLE
Only few releases are picked.

### DISCUSSION THREAD

**Discussion by nikhilbadyal** [crazy-max/ghaction-virustotal#177] [Q&A]
### Behaviour
 I had a release that contained 4 APK files. Out of those 4 files. I can only see the analysis of 2 files.

#### Expected behavior

All 4 files should be sent for a scan.

#### Actual behaviour

Only 2 files were sent for a scan.

### Configuration

* Repository URL (if public): [Repo](https://github.com/nikhilbadyal/docker-py-revanced)
* Build URL (if public): [Build](https://github.com/nikhilbadyal/docker-py-revanced/runs/7830711582?check_suite_focus=true#step:2:12])

```yml
name: VirusTotal Scan

on:
  release:
    types: [published]
  workflow_dispatch: # to trigger manually

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          github_token: ${{ secrets.GH_TOKEN }}
          files: |
            .apk$

```
