### ISSUE TITLE
Axios limits max file size

### ISSUE THREAD

**Issue by grctest** [crazy-max/ghaction-virustotal#133]
### Behaviour

Unable to upload a large file to virustotal with action.

#### Steps to reproduce this issue

1. Create a file with size 140MB (React + Electron app)
2. Attempt to upload via action
3. Get error

#### Expected behaviour

File is uploaded to virustotal via upload url, well within larger file size limits.

#### Actual behaviour

The following error is output: `AxiosError: Request failed with status code 413`

### Configuration

```yml
    - name: VirusTotal Monitor Scan
      uses: crazy-max/ghaction-virustotal@v3
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        vt_monitor: true
        request_rate: 2
        monitor_path: /home/runner/
        files: |
          /home/runner/nft_viewer.exe
          /home/runner/nft_viewer.deb
```

### Logs

```
Cannot send nft_viewer.exe to VirusTotal Monitor at /home/runner/nft_viewer.exe: AxiosError: Request failed with status code 413
```
