### ISSUE TITLE
AxiosError code 401

### ISSUE THREAD

**Issue by dreamwhite** [crazy-max/ghaction-virustotal#142]
#### Steps to reproduce this issue

1. Configure GitHub-CI with [this](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/blob/master/.github/workflows/virustotal.yml) workflow file
2. Trigger the GitHub Action (automatically triggered via push rule) 
3. Check the [logs](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/actions/runs/3288625737/jobs/5419191516#step:3:18)

#### Expected behaviour

It should upload the file

#### Actual behaviour

It raises a 401 error.

### Configuration

* Repository URL (if public): https://github.com/dreamwhite/dell-inspiron-5370-hackintosh
* Build URL (if public): don't have one to be fair, just wanted to scan the files in my repo

```yml
name: VirusTotal scan
on:
  workflow_call:

jobs:
  virustotal:
    name: VirusTotal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            EFI/BOOT/*.efi
            EFI/OC/ACPI/*.aml
            EFI/OC/Drivers/*.efi
            EFI/OC/Kexts/*.kext/*/*/*
            EFI/OC/Kexts/*.kext/*/PlugIns/*/*/*
            EFI/OC/Tools/*.efi
          update_release_body: true
          request_rate: 4

```

### Logs

[logs_61.zip](https://github.com/crazy-max/ghaction-virustotal/files/9828689/logs_61.zip)
