### ISSUE TITLE
Wildcards Don't Actually Work

### ISSUE THREAD

**Issue by simeononsecurity** [crazy-max/ghaction-virustotal#160]
```yml
name: VirusTotal Scan

on:
  pull_request:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan files
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            *.html
            *.ps1
```            
 Also have tried 
 ```yml
name: VirusTotal Scan

on:
  pull_request:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan files
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            .html*
            .ps1*
```

**Comment by LukeSavefrogs** [comment]
I have the opposite problem @crazy-max 😁

The following **will not work** as expected (`.exe$` is taken from the README) and instead show the `No files were found. Please check the 'files' input.` warning:
```yaml
jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls -l *.exe
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vt_api_key: ${{ secrets.VIRUSTOTAL_TOKEN }}
          files: |
            .exe$
```

The following instead **will correctly upload** the `.exe` file to VirusTotal as expected:
```
jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls -l *.exe
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vt_api_key: ${{ secrets.VIRUSTOTAL_TOKEN }}
          files: |
            *.exe
```

In conclusion **glob patterns seem to work**, while regex don't (?), event hough the documentation clearly suggests to use regexes.
