### ISSUE TITLE
Action fails to run - Invalid regular expression: /*.exe/: Nothing to repeat

### ISSUE THREAD

**Issue by tryallthethings** [crazy-max/ghaction-virustotal#49]
### Behaviour
The GitHub Action to check a releases' files on VirusTotal always fails with
`Invalid regular expression: /*.exe/: Nothing to repeat`

#### Steps to reproduce this issue

1. Create new GitHub Action .yml as per instructions on https://github.com/marketplace/actions/virustotal-github-action#scan-assets-of-a-published-release
2. Publish a new release

#### Expected behaviour

> The Action should run and update the release with the analysis report

#### Actual behaviour

> Action fails with error

`Invalid regular expression: /*.exe/: Nothing to repeat`

### Configuration

* Repository URL (if public): https://github.com/tryallthethings/Discord-Disco
* Build URL (if public): ?

```yml
name: VirusTotal release scan

on:
  release:
    types: [published]

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          github_token: ${{ github.token }}
          update_release_body: true
          files: |
              *.exe
```

### Logs

> [logs_6.zip](https://github.com/crazy-max/ghaction-virustotal/files/5178929/logs_6.zip)
