### ISSUE TITLE
Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by Milerius** [crazy-max/ghaction-virustotal#60]
#### Steps to reproduce this issue

https://github.com/smk762/atomicDEX-Desktop/runs/1502695126?check_suite_focus=true

```
🔔 Release event detected for refs/tags/0.3.1-beta2 in this workflow. Preparing to scan assets...
📦 1 asset(s) will be sent to VirusTotal for analysis.
⬇️ Downloading atomicdex-desktop-0.3.1-beta-windows.zip...
Error: Request body larger than maxBodyLength limit
```

**Comment by crazy-max** [comment]
@Milerius I've pushed a fix to enhanced error message output. Can you try again?

**Comment by umbynos** [comment]
I'm having the same problem.
I'm trying to upload a binary to virustotal using your action.
This is the workflow I'm using:
```
name: released

on:
  release:
    types: [published]

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2.3.0
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          update_release_body: true
          files: |
            .exe$
```
And the error is: `Error: Cannot send ArduinoCreateAgent-1.2-windows-386-installer-chrome.exe to VirusTotal: Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit`

Before finding that issue I tried using V2 (as stated in the README.md) but the issue stays the same.
I'm trying to upload a 18.3 MB file, so it's well below the 32MB limit. I do not understand what's the problem
